=== logos106/ERPNew/Utils/DtdToXml/3C3_MS_V01_01_InvoiceNotification.dtd
<!-- 

RosettaNet XML Message Schema
3C3_MS_V01_01_InvoiceNotification.dtd (7-Mar-2003 2:41:16 PM)
This document has been prepared by RosettaNet (http://www.rosettanet.org) from requirements gathered during the cluster/segment workshops and in conformance with the RosettaNet methodology.

-->

<!ENTITY % common-attributes "id CDATA #IMPLIED">

<!ELEMENT Pip3C3InvoiceNotification
	(fromRole, 
	 GlobalDocumentFunctionCode?, 
	 Invoice, 
	 thisDocumentGenerationDateTime, 
	 thisDocumentIdentifier, 
	 toRole)>

<!ELEMENT fromRole
	(PartnerRoleDescription)>

<!ELEMENT PartnerRoleDescription
	(ContactInformation?, 
	 GlobalPartnerRoleClassificationCode, 
	 PartnerDescription)>

<!ELEMENT ContactInformation
	(contactName, 
	 EmailAddress, 
	 facsimileNumber?, 
	 telephoneNumber?)>

<!ELEMENT contactName
	(FreeFormText)>

<!ELEMENT FreeFormText
	(#PCDATA)>

<!ATTLIST FreeFormText xml:lang CDATA #IMPLIED >

<!ELEMENT EmailAddress
	(#PCDATA)>

<!ELEMENT facsimileNumber
	(CommunicationsNumber)>

<!ELEMENT CommunicationsNumber
	(#PCDATA)>

<!ELEMENT telephoneNumber
	(CommunicationsNumber)>

<!ELEMENT GlobalPartnerRoleClassificationCode
	(#PCDATA)>

<!ELEMENT PartnerDescription
	(BusinessDescription, 
	 GlobalPartnerClassificationCode?, 
	 PhysicalLocation?)>

<!ELEMENT BusinessDescription
	(GlobalBusinessIdentifier?, 
	 GlobalSupplyChainCode?, 
	 businessName?, 
	 NationalBusinessTaxIdentifier?, 
	 PartnerBusinessIdentification*, 
	 RegionalBusinessTaxIdentifier?)>

<!ELEMENT GlobalBusinessIdentifier
	(#PCDATA)>

<!ELEMENT GlobalSupplyChainCode
	(#PCDATA)>

<!ELEMENT GlobalPartnerClassificationCode
	(#PCDATA)>

<!ELEMENT GlobalDocumentFunctionCode
	(#PCDATA)>

<!ELEMENT Invoice
	(ancillaryAmount*, 
	 billFrom, 
	 billTo, 
	 billToAccount*, 
	 Financing?, 
	 GlobalDocumentTypeCode, 
	 GlobalPaymentTermsCode?, 
	 GlobalSaleTypeCode?, 
	 InvoiceLineItem+, 
	 isLockBoxUsed, 
	 isRebill, 
	 originalInvoiceNumber?, 
	 preTaxAmount?, 
	 proprietaryInformation?, 
	 purchaseOrderNumber?, 
	 remitTo?, 
	 remitToAccount*, 
	 remitToTax?, 
	 salesOrderIdentifier*, 
	 soldTo?, 
	 soldToAccount*, 
	 soldToTax?, 
	 totalInvoiceAmount, 
	 transferTo?, 
	 transferToAccount*)>

<!ELEMENT ancillaryAmount
	(FinancialAmount)>

<!ELEMENT FinancialAmount
	(GlobalCurrencyCode, 
	 GlobalMonetaryAmountTypeCode?, 
	 InvoiceChargeTypeCode?, 
	 MonetaryAmount)>

<!ELEMENT GlobalCurrencyCode
	(#PCDATA)>

<!ELEMENT GlobalMonetaryAmountTypeCode
	(#PCDATA)>

<!ELEMENT InvoiceChargeTypeCode
	(#PCDATA)>

<!ELEMENT MonetaryAmount
	(#PCDATA)>

<!ELEMENT billFrom
	(PartnerTaxDescription)>

<!ELEMENT PartnerTaxDescription
	(BusinessDescription, 
	 ContactInformation?, 
	 GlobalPartnerClassificationCode, 
	 PhysicalLocation?)>

<!ELEMENT businessName
	(FreeFormText)>

<!ELEMENT NationalBusinessTaxIdentifier
	(BusinessTaxIdentifier, 
	 GlobalCountryCode)>

<!ELEMENT BusinessTaxIdentifier
	(#PCDATA)>

<!ELEMENT GlobalCountryCode
	(#PCDATA)>

<!ELEMENT PartnerBusinessIdentification
	(ProprietaryBusinessIdentifier, 
	 ProprietaryDomainIdentifier, 
	 ProprietaryIdentifierAuthority?)>

<!ELEMENT ProprietaryBusinessIdentifier
	(#PCDATA)>

<!ELEMENT ProprietaryDomainIdentifier
	(#PCDATA)>

<!ELEMENT ProprietaryIdentifierAuthority
	(#PCDATA)>

<!ELEMENT RegionalBusinessTaxIdentifier
	(BusinessTaxIdentifier, 
	 regionName)>

<!ELEMENT regionName
	(FreeFormText)>

<!ELEMENT PhysicalLocation
	(GlobalLocationIdentifier?, 
	 PartnerLocationIdentification*, 
	 PhysicalAddress?)>

<!ELEMENT GlobalLocationIdentifier
	(#PCDATA)>

<!ELEMENT PartnerLocationIdentification
	(ProprietaryDomainIdentifier, 
	 ProprietaryIdentifierAuthority?, 
	 ProprietaryLocationIdentifier)>

<!ELEMENT ProprietaryLocationIdentifier
	(#PCDATA)>

<!ELEMENT PhysicalAddress
	(addressLine1?, 
	 addressLine2?, 
	 addressLine3?, 
	 cityName?, 
	 GlobalCountryCode?, 
	 NationalPostalCode?, 
	 postOfficeBoxIdentifier?, 
	 regionName?)>

<!ELEMENT addressLine1
	(FreeFormText)>

<!ELEMENT addressLine2
	(FreeFormText)>

<!ELEMENT addressLine3
	(FreeFormText)>

<!ELEMENT cityName
	(FreeFormText)>

<!ELEMENT NationalPostalCode
	(#PCDATA)>

<!ELEMENT postOfficeBoxIdentifier
	(FreeFormText)>

<!ELEMENT billTo
	(PartnerTaxDescription)>

<!ELEMENT billToAccount
	(AccountNumber)>

<!ELEMENT AccountNumber
	(#PCDATA)>

<!ELEMENT Financing
	(approvalIdentifier, 
	 financingPlanIdentifier?)>

<!ELEMENT approvalIdentifier
	(ProprietaryReferenceIdentifier)>

<!ELEMENT ProprietaryReferenceIdentifier
	(#PCDATA)>

<!ELEMENT financingPlanIdentifier
	(ProprietaryReferenceIdentifier)>

<!ELEMENT GlobalDocumentTypeCode
	(#PCDATA)>

<!ELEMENT GlobalPaymentTermsCode
	(#PCDATA)>

<!ELEMENT GlobalSaleTypeCode
	(#PCDATA)>

<!ELEMENT InvoiceLineItem
	(invoiceAmount*, 
	 LineNumber, 
	 OrderStatus, 
	 packingSlipIdentifier?, 
	 PrePaymentDetail?, 
	 preTaxAmount?, 
	 proprietaryInformation?, 
	 shipTo?, 
	 shipToAccount*, 
	 totalLineItemAmount, 
	 transportedBy?, 
	 transportedByAccount*)>

<!ELEMENT invoiceAmount
	(FinancialAmount)>

<!ELEMENT LineNumber
	(#PCDATA)>

<!ELEMENT OrderStatus
	(primaryIdentifier?, 
	 PurchaseOrder, 
	 secondaryIdentifier?)>

<!ELEMENT primaryIdentifier
	(ProprietaryShipmentTrackingIdentifier)>

<!ELEMENT ProprietaryShipmentTrackingIdentifier
	(#PCDATA)>

<!ELEMENT PurchaseOrder
	(GlobalShipmentTermsCode?, 
	 governmentContractIdentifier?, 
	 ProductLineItem+, 
	 purchaseOrderNumber?)>

<!ELEMENT GlobalShipmentTermsCode
	(#PCDATA)>

<!ELEMENT governmentContractIdentifier
	(ProprietaryDocumentIdentifier)>

<!ELEMENT ProprietaryDocumentIdentifier
	(#PCDATA)>

<!ELEMENT ProductLineItem
	(countryOfOrigin?, 
	 GlobalProductUnitOfMeasureCode, 
	 GlobalShippingServiceLevelCode?, 
	 LineNumber, 
	 ProductDescription, 
	 ProductQuantity, 
	 shipDate?, 
	 shipFrom*, 
	 TaxSummary?, 
	 unitPrice)>

<!ELEMENT countryOfOrigin
	(GlobalCountryCode)>

<!ELEMENT GlobalProductUnitOfMeasureCode
	(#PCDATA)>

<!ELEMENT GlobalShippingServiceLevelCode
	(#PCDATA)>

<!ELEMENT ProductDescription
	(LotIdentification?, 
	 NationalExportControlClassificationCode?, 
	 NationalHarmonizedTariffScheduleCode?, 
	 ProductIdentification, 
	 ProprietarySerialIdentifier?)>

<!ELEMENT LotIdentification
	(primaryLotIdentifier, 
	 secondaryLotIdentifier?)>

<!ELEMENT primaryLotIdentifier
	(ProprietaryReferenceIdentifier)>

<!ELEMENT secondaryLotIdentifier
	(ProprietaryReferenceIdentifier)>

<!ELEMENT NationalExportControlClassificationCode
	(#PCDATA)>

<!ELEMENT NationalHarmonizedTariffScheduleCode
	(#PCDATA)>

<!ELEMENT ProductIdentification
	(GlobalProductIdentifier?, 
	 PartnerProductIdentification*)>

<!ELEMENT GlobalProductIdentifier
	(#PCDATA)>

<!ELEMENT PartnerProductIdentification
	(GlobalPartnerClassificationCode, 
	 ProprietaryProductIdentifier, 
	 revisionIdentifier?)>

<!ELEMENT ProprietaryProductIdentifier
	(#PCDATA)>

<!ELEMENT revisionIdentifier
	(FreeFormText)>

<!ELEMENT ProprietarySerialIdentifier
	(#PCDATA)>

<!ELEMENT ProductQuantity
	(#PCDATA)>

<!ELEMENT shipDate
	(DateStamp)>

<!ELEMENT DateStamp
	(#PCDATA)>

<!ELEMENT shipFrom
	(PartnerTaxDescription)>

<!ELEMENT TaxSummary
	(CityTax?, 
	 NationalTax?, 
	 RegionalTax?, 
	 TaxPhrase?, 
	 totalAmount?, 
	 CurrencyConversion?, 
	 FinancialAmount?)>

<!ELEMENT CityTax
	(cityName, 
	 FinancialAmount, 
	 taxRate?)>

<!ELEMENT taxRate
	(PercentAmount)>

<!ELEMENT PercentAmount
	(#PCDATA)>

<!ELEMENT NationalTax
	(FinancialAmount, 
	 NationalBusinessTaxIdentifier, 
	 taxRate?)>

<!ELEMENT RegionalTax
	(FinancialAmount, 
	 RegionalBusinessTaxIdentifier, 
	 taxRate?)>

<!ELEMENT TaxPhrase
	(isTaxTriangulationApplicable, 
	 taxPhrase?)>

<!ELEMENT isTaxTriangulationApplicable
	(AffirmationIndicator)>

<!ELEMENT AffirmationIndicator
	(#PCDATA)>

<!ELEMENT taxPhrase
	(FreeFormText)>

<!ELEMENT totalAmount
	(FinancialAmount)>

<!ELEMENT unitPrice
	(FinancialAmount)>

<!ELEMENT purchaseOrderNumber
	(ProprietaryDocumentIdentifier)>

<!ELEMENT secondaryIdentifier
	(ProprietaryShipmentTrackingIdentifier)>

<!ELEMENT packingSlipIdentifier
	(ProprietaryDocumentIdentifier)>

<!ELEMENT PrePaymentDetail
	(DateStamp*, 
	 FinancialAmount?)>

<!ELEMENT preTaxAmount
	(FinancialAmount)>

<!ELEMENT proprietaryInformation
	(FreeFormText)>

<!ELEMENT shipTo
	(PartnerTaxDescription)>

<!ELEMENT shipToAccount
	(AccountNumber)>

<!ELEMENT totalLineItemAmount
	(FinancialAmount)>

<!ELEMENT transportedBy
	(PartnerDescription)>

<!ELEMENT transportedByAccount
	(AccountNumber)>

<!ELEMENT isLockBoxUsed
	(AffirmationIndicator)>

<!ELEMENT isRebill
	(AffirmationIndicator)>

<!ELEMENT originalInvoiceNumber
	(ProprietaryDocumentIdentifier)>

<!ELEMENT remitTo
	(PartnerTaxDescription)>

<!ELEMENT remitToAccount
	(AccountSummary)>

<!ELEMENT AccountSummary
	(AccountNumber?, 
	 BankKey?, 
	 GlobalBankIdentifier?)>

<!ELEMENT BankKey
	(#PCDATA)>

<!ELEMENT GlobalBankIdentifier
	(#PCDATA)>

<!ELEMENT remitToTax
	(TaxSummary)>

<!ELEMENT CurrencyConversion
	(conversionFactor, 
	 conversionFactorDate, 
	 conversionFactorSource, 
	 fromCurrency, 
	 toCurrency)>

<!ELEMENT conversionFactor
	(CurrencyExchangeRate)>

<!ELEMENT CurrencyExchangeRate
	(#PCDATA)>

<!ELEMENT conversionFactorDate
	(DateStamp)>

<!ELEMENT conversionFactorSource
	(ProprietaryReferenceIdentifier)>

<!ELEMENT fromCurrency
	(GlobalCurrencyCode)>

<!ELEMENT toCurrency
	(GlobalCurrencyCode)>

<!ELEMENT salesOrderIdentifier
	(ProprietaryDocumentIdentifier)>

<!ELEMENT soldTo
	(PartnerDescription)>

<!ELEMENT soldToAccount
	(AccountNumber)>

<!ELEMENT soldToTax
	(TaxSummary)>

<!ELEMENT totalInvoiceAmount
	(FinancialAmount)>

<!ELEMENT transferTo
	(PartnerDescription)>

<!ELEMENT transferToAccount
	(AccountNumber)>

<!ELEMENT thisDocumentGenerationDateTime
	(DateTimeStamp)>

<!ELEMENT DateTimeStamp
	(#PCDATA)>

<!ELEMENT thisDocumentIdentifier
	(ProprietaryDocumentIdentifier)>

<!ELEMENT toRole
	(PartnerRoleDescription)>

=== logos106/ERPNew/Utils/DtdToXml/3C3_MS_V01_01_InvoiceNotification.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Pip3C3InvoiceNotification SYSTEM "3C3_MS_V01_01_InvoiceNotification.dtd">
<Pip3C3InvoiceNotification>
	<fromRole>
		<PartnerRoleDescription>
			<GlobalPartnerRoleClassificationCode></GlobalPartnerRoleClassificationCode>
			<PartnerDescription>
				<BusinessDescription>
				</BusinessDescription>
			</PartnerDescription>
		</PartnerRoleDescription>
	</fromRole>
	<Invoice>
		<billFrom>
			<PartnerTaxDescription>
				<BusinessDescription>
				</BusinessDescription>
				<GlobalPartnerClassificationCode></GlobalPartnerClassificationCode>
			</PartnerTaxDescription>
		</billFrom>
		<billTo>
			<PartnerTaxDescription>
				<BusinessDescription>
				</BusinessDescription>
				<GlobalPartnerClassificationCode></GlobalPartnerClassificationCode>
			</PartnerTaxDescription>
		</billTo>
		<GlobalDocumentTypeCode></GlobalDocumentTypeCode>
		<InvoiceLineItem>
			<LineNumber></LineNumber>
			<OrderStatus>
				<PurchaseOrder>
					<ProductLineItem>
						<GlobalProductUnitOfMeasureCode></GlobalProductUnitOfMeasureCode>
						<LineNumber></LineNumber>
						<ProductDescription>
							<ProductIdentification>
							</ProductIdentification>
						</ProductDescription>
						<ProductQuantity></ProductQuantity>
						<unitPrice>
							<FinancialAmount>
								<GlobalCurrencyCode></GlobalCurrencyCode>
								<MonetaryAmount></MonetaryAmount>
							</FinancialAmount>
						</unitPrice>
					</ProductLineItem>
				</PurchaseOrder>
			</OrderStatus>
			<totalLineItemAmount>
				<FinancialAmount>
					<GlobalCurrencyCode></GlobalCurrencyCode>
					<MonetaryAmount></MonetaryAmount>
				</FinancialAmount>
			</totalLineItemAmount>
		</InvoiceLineItem>
		<isLockBoxUsed>
			<AffirmationIndicator></AffirmationIndicator>
		</isLockBoxUsed>
		<isRebill>
			<AffirmationIndicator></AffirmationIndicator>
		</isRebill>
		<totalInvoiceAmount>
			<FinancialAmount>
				<GlobalCurrencyCode></GlobalCurrencyCode>
				<MonetaryAmount></MonetaryAmount>
			</FinancialAmount>
		</totalInvoiceAmount>
	</Invoice>
	<thisDocumentGenerationDateTime>
		<DateTimeStamp></DateTimeStamp>
	</thisDocumentGenerationDateTime>
	<thisDocumentIdentifier>
		<ProprietaryDocumentIdentifier></ProprietaryDocumentIdentifier>
	</thisDocumentIdentifier>
	<toRole>
		<PartnerRoleDescription>
			<GlobalPartnerRoleClassificationCode></GlobalPartnerRoleClassificationCode>
			<PartnerDescription>
				<BusinessDescription>
				</BusinessDescription>
			</PartnerDescription>
		</PartnerRoleDescription>
	</toRole>
</Pip3C3InvoiceNotification>
